AppPagina/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.inicio,name='inicio'),
    #path urls buscar de clases
    path('buscarCliente/',views.buscarCliente, name='buscarCliente'),
    path('buscarArticulo/',views.buscarArticulo, name='buscarArticulo'),
    
    
    #path login y logout
    path('login/',views.login_request, name='login'),
    path('registro/',views.registro, name='registro'),
    path('logout/', LogoutView.as_view(template_name='AppPagina/logout.html'), name='logout'),
    
    #path urls de articulo
    path('articulo/nuevo/',views.ArticuloCreateView.as_view(), name='articulo'),
    path('articulo/lista/', views.ArticuloListView.as_view(), name = 'articulo_list'),
    path('articulo/<pk>/borrar/', views.ArticuloDeleteView.as_view(), name='ArticuloDeleteView'),
    path('articulo/<pk>/', views.ArticuloDetailView.as_view(), name='ArticuloDetailView'),
    path('articulo/<pk>/editar/', views.ArticuloUpdateView.as_view(), name='ArticuloUpdateView'),
    
    #path urls de vendedor
    path('vendedor/lista/', views.VendedorListView.as_view(), name = 'vendedor_list'),
    path('vendedor/nuevo/', views.VendedorCreateView.as_view(), name='vendedor'),
    path('vendedor/<pk>/borrar/', views.VendedorDeleteView.as_view(), name='VendedorDeleteView'),
    path('vendedor/<pk>/', views.VendedorDetailView.as_view(), name='VendedorDetailView'),
    path('vendedor/<pk>/editar/', views.VendedorUpdateView.as_view(), name='VendedorUpdateView'),
    
    #path urls de cliente
    path('cliente/nuevo/', views.ClienteCreateView.as_view(), name='cliente'),
    path('cliente/lista/', views.ClienteListView.as_view(), name = 'cliente_list'),
    path('cliente/<pk>/borrar/', views.ClienteDeleteView.as_view(), name='ClienteDeleteView'),
    path('cliente/<pk>/editar/', views.ClienteUpdateView.as_view(), name='ClienteUpdateView'),
    path('cliente/<pk>/', views.ClienteDetailView.as_view(), name='ClienteDetailView'),
    
    
    #path urls de post
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    
    
]

TuPrimerPagina_Roca/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppPagina/', include(('AppPagina.urls', 'AppPagina'), namespace='AppPagina')),
]

AppPagina/models.py
from django.db import models

# Create your models here.
class Articulo(models.Model):
    nombre = models.CharField(max_length=40)
    marca = models.CharField(max_length=40)
    tipo = models.CharField(max_length=40)
    precio = models.FloatField()
    
    def __str__(self):
        return self.nombre

    
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    dni = models.CharField(max_length=10)
    email = models.EmailField(default='modelo@example.com')

class Vendedor(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    dni = models.CharField(max_length=10)
    num_vendedor = models.IntegerField()
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

AppPagina/forms.py
from django import forms
from .models import Articulo, Cliente, Vendedor, Post
from django.contrib.auth.forms import UserCreationForm, UserModel

class ClienteFormulario(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
    

class ArticuloFormulario(forms.ModelForm):
    class Meta:
        model = Articulo
        fields ='__all__'
        

class VendedorFormulario(forms.ModelForm):
    class Meta:
        model = Vendedor
        fields  ='__all__'
        
class ClienteSearchForm(forms.Form):
    nombre = forms.CharField(required=False)

class ArticuloSearchForm(forms.Form):
    nombre = forms.CharField(required=False)
    
class UserCreationFormCustom(UserCreationForm):
    username = forms.CharField(label = "Usuario")
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget= forms.PasswordInput)
    password2 = forms.CharField(label="Repetir Contraseña", widget= forms.PasswordInput)
    class Meta:
        model = UserModel
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        

AppPagina/views.py
from django.shortcuts import render, redirect
from django.template import Template,Context,loader
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cliente,Articulo, Vendedor, Post
from .forms import PostForm, ArticuloFormulario, ArticuloSearchForm, ClienteSearchForm, UserCreationFormCustom
#login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
#login 
#--------------------------------------------------------------------------------------------------
def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            
            user = authenticate(username = usuario, password= contrasenia)
            
            login(request, user)
            
            return render(request,'AppPagina/inicio.html',{"mensaje": f'Bienvenido {user.username}'} )
    
    else:
        form = AuthenticationForm()
        
    return render (request, 'AppPagina/login.html', {'form': form})

def registro(request):
    if request.method == 'POST':
        form = UserCreationFormCustom(request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            form.save()
                        
            return render(request,'AppPagina/inicio.html',{"mensaje": "usuario creado" })
    
    else:
        form = UserCreationFormCustom()
        
    return render (request, 'AppPagina/registro.html', {'form': form})
    



#--------------------------------------------------------------------------------------------------
@login_required
def inicio(request):
    return render(request,'AppPagina/inicio.html')


def buscarCliente(request):
    clientes = []
    form = ClienteSearchForm(request.GET)

    if form.is_valid():
        nombre = form.cleaned_data.get('nombre')

        # Realizar la búsqueda en el modelo Curso por nombre
        if nombre:
            clientes= Cliente.objects.filter(nombre__icontains=nombre)

    return render(request, 'AppPagina/buscarCliente.html', {'form': form, 'clientes': clientes})

def buscarArticulo(request):
    articulos = []
    form = ArticuloSearchForm(request.GET)

    if form.is_valid():
        nombre = form.cleaned_data.get('nombre')

        # Realizar la búsqueda en el modelo Curso por nombre
        if nombre:
            articulos= Articulo.objects.filter(nombre__icontains=nombre)

    return render(request, 'AppPagina/buscarArticulo.html', {'form': form, 'articulos': articulos})

#cliente vistas
#---------------------------------------------------------------------------------
class ClienteListView(ListView):
    model = Cliente
    template_name = 'AppPagina/cliente_list.html'
    context_object_name = 'cliente'

class ClienteCreateView(LoginRequiredMixin, CreateView):
    model = Cliente
    fields = ['nombre', 'apellido', 'dni', 'email']
    template_name= 'AppPagina/cliente.html'
    success_url = reverse_lazy('AppPagina:cliente_list')

class ClienteDeleteView(LoginRequiredMixin, DeleteView):
    model = Cliente
    template_name = 'AppPagina/cliente_delete.html'
    success_url = reverse_lazy('AppPagina:cliente_list')
    
class ClienteDetailView(LoginRequiredMixin, DetailView):
    model = Cliente
    template_name = 'AppPagina/cliente_detalle.html'

class ClienteUpdateView(LoginRequiredMixin, UpdateView):
    model = Cliente
    fields = ['nombre', 'apellido', 'dni', 'email']
    template_name ='AppPagina/cliente_update.html'
    success_url = reverse_lazy('AppPagina:cliente_list')
    
    

#vendedor vistas
#---------------------------------------------------------------------------------
class VendedorListView(ListView):
    model = Vendedor
    template_name ='AppPagina/vendedor_list.html'
    context_object_name = 'vendedor'

class VendedorCreateView(LoginRequiredMixin, CreateView):
    model = Vendedor
    fields = ['nombre', 'apellido', 'dni', 'num_vendedor']
    template_name = 'AppPagina/vendedor.html'
    success_url = reverse_lazy('AppPagina:vendedor_list')

class VendedorDeleteView(LoginRequiredMixin, DeleteView):
    model = Vendedor
    template_name = 'AppPagina/vendedor_delete.html'
    success_url = reverse_lazy('AppPagina:vendedor_list')

class VendedorDetailView(LoginRequiredMixin, DetailView):
    model = Vendedor
    template_name = 'AppPagina/vendedor_detalle.html'

class VendedorUpdateView(LoginRequiredMixin,UpdateView):
    model = Vendedor
    fields = ['nombre', 'apellido', 'dni', 'num_vendedor']
    template_name ='AppPagina/vendedor_update.html'
    success_url = reverse_lazy('AppPagina:vendedor_list')


#articulos vistas
#---------------------------------------------------------------------------------
class ArticuloListView(ListView):
    model = Articulo
    template_name = 'AppPagina/articulo_list.html'
    context_object_name = 'articulo'

class ArticuloCreateView(LoginRequiredMixin, CreateView):
    model = Articulo
    fields = ['nombre', 'marca', 'tipo', 'precio']
    template_name = 'AppPagina/articulos.html'
    success_url = reverse_lazy('AppPagina:articulo_list')
        
class ArticuloDeleteView(LoginRequiredMixin, DeleteView):
    model = Articulo
    template_name = 'AppPagina/articulo_delete.html'
    success_url = reverse_lazy('AppPagina:articulo_list')

class ArticuloDetailView(DetailView):
    model = Articulo
    template_name = 'AppPagina/articulo_detalle.html'
    
class ArticuloUpdateView(LoginRequiredMixin, UpdateView):
    model = Articulo
    fields = ['nombre', 'marca', 'tipo', 'precio']
    template_name ='AppPagina/articulo_update.html'
    success_url = reverse_lazy('AppPagina:articulo_list')



#Post
#-------------------------------------------------------------------------------------------
class PostListView(ListView):
    model = Post
    template_name = 'AppPagina/post_list.html'
    context_object_name = 'posts'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'AppPagina/post_create.html'
    success_url = reverse_lazy('AppPagina:post_list')

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'AppPagina/post_update.html'
    success_url = reverse_lazy('AppPAgina:post_list')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'AppPagina/post_delete.html'
    success_url = reverse_lazy('AppPagina:post_list')    
    
    

AppPagina/templates/AppPagina/articulo_list.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Lista articulos </h1>
{%endblock titulo%}

{% block contenido %}

    
</div>

<div class = "conteiner">
    <h3 class = "mb-4" > Listar articulos </h3>
    <a href = "{% url 'AppPagina:articulo'%}"> Nuevo Articulo </a></br>
    <a href = "{% url 'AppPagina:buscarArticulo'%}"> Buscar Articulo </a>
    <ul class = "list-group">
        {%for c in articulo%}
        <li class ="list-group-item">
            <p> {{c.nombre}} - {{c.marca}} - {{c.tipo}} - {{c.precio}}
                <a href = "{% url 'AppPagina:ArticuloDetailView' c.pk %}"> Ver</a>
                <a href = "{% url 'AppPagina:ArticuloUpdateView' c.pk %}"> Editar </a>
                <a href="{% url 'AppPagina:ArticuloDeleteView' c.pk %}"> Borrar </a>
            </p>
        </li>
        {%endfor%}
    </ul>
</div>
{% endblock contenido%}

AppPagina/templates/AppPagina/articulo_update.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Editar Articulo </h1>
{%endblock titulo%}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Editar">
</form>
<a href = "{% url 'AppPagina:articulo_list'%}"> volver </a>
{%endblock contenido%}

AppPagina/templates/AppPagina/buscarArticulo.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Buscar articulo </h1>
{%endblock titulo%}
    
    
    {%block contenido%}

        <h1>Buscar Articulo por Nombre</h1>
        <form method="get" action="">
            {{ form.as_p }}
            <button type="submit">Buscar</button>

        </form>

        {% if articulos %}
        <h2>Resultados de la búsqueda:</h2>
        <ul>
            {% for articulo in articulos %}
            <li>{{articulo.nombre}} - {{articulo.marca}} - {{articulo.tipo}} - {{articulo.precio}}
                <a href = ""> Ver</a>
                <a href = ""> Editar </a>
                <a href="{% url 'AppPagina:ArticuloDeleteView' articulo.pk %}"> Borrar </a>
            </li>
            {% endfor %}
        </ul>
        

        {% else %}
        <h3>no hay resultados</h3>
        {% endif %}
        <a href = "{% url 'AppPagina:articulo_list'%}"> volver </a>
        {% endblock contenido%}

AppPagina/templates/AppPagina/buscarCliente.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Buscar cliente </h1>
{%endblock titulo%}
    
    
    {%block contenido%}

        <h1>Buscar Cliente por Nombre</h1>
        <form method="get" action="">
            {{ form.as_p }}
            <button type="submit">Buscar</button>

        </form>

        {% if clientes %}
        <h2>Resultados de la búsqueda:</h2>
        <ul>
            {% for cliente in clientes %}
            <li>{{ cliente.nombre }}  {{ cliente.apellido }} - dni : {{cliente.dni}} - mail: {{cliente.email}}</li>
            {% endfor %}
        </ul>
        

        {% else %}
        <h3>no hay resultados</h3>
        {% endif %}

        {% endblock contenido%}

AppPagina/templates/AppPagina/cliente.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Cliente Formulario </h1>
{%endblock titulo%}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Enviar">
</form>

<a href = "{% url 'AppPagina:cliente_list'%}"> volver </a>
{% endblock contenido%}

AppPagina/templates/AppPagina/cliente_list.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Lista Cliente </h1>
{%endblock titulo%}

{% block contenido %}
<div class = "conteiner">
    <h3 class = "mb-4" > Listar Clientes </h3>
    <a href = "{% url 'AppPagina:cliente'%}"> Nuevo Cliente </a></br>
    <a href = "{% url 'AppPagina:buscarCliente'%}"> Buscar Cliente </a>

    <ul class = "list-group">
        {%for c in cliente%}
        <li class ="list-group-item">
            <p> {{c.nombre}} {{c.apellido}} - dni : {{c.dni}} - email : {{c.email}}
                <a href = "{% url 'AppPagina:ClienteDetailView' c.pk %}"> Ver</a>
                <a href = "{% url 'AppPagina:ClienteUpdateView' c.pk %}"> Editar </a>
                <a href="{% url 'AppPagina:ClienteDeleteView' c.pk %}"> Borrar </a>
            </p>
        </li>
        {%endfor%}
    </ul>
    
</div>
{% endblock contenido%}

AppPagina/templates/AppPagina/login.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{% block contenido %}
<h1> Login </h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Iniciar Sesion </button>
    <a href="{% url 'AppPagina:registro' %}"> ¿No tienes cuenta?</a>
</form>

{% endblock contenido%}

AppPagina/templates/AppPagina/logout.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{% block contenido %}
<h1> Te has deslogueado </h1>

{% endblock contenido%}

AppPagina/templates/AppPagina/post_delete.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{% block contenido %}
<h1>Eliminar Post</h1>
  <p>¿Estás seguro de que deseas eliminar el post "{{ post.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
  </form>

{% endblock contenido%}

AppPagina/templates/AppPagina/post_list.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{% block contenido %}
<h1>Lista de Posts</h1>
  <ul class="list-group">
    {% for post in posts %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <a href="{% url 'AppPagina:post_update' post.pk %}">{{ post.title }}</a>
          <div>
            <a href="{% url 'AppPagina:post_delete' post.pk %}" class="btn btn-danger btn-sm ml-2">Eliminar</a>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'AppPagina:post_create' %}" class="btn btn-primary mt-3">Crear nuevo post</a>

{% endblock contenido%}

AppPagina/templates/AppPagina/registro.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{% block contenido %}
<h1> Registro </h1>

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button type="submit">Registrate </button>
</form>

{% endblock contenido%}

AppPagina/templates/AppPagina/vendedor.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Vendedor Formulario </h1>
{%endblock titulo%}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Enviar">
</form>
<a href = "{% url 'AppPagina:vendedor_list'%}"> volver </a>
{%endblock contenido%}

AppPagina/templates/AppPagina/vendedor_detalle.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Detalles del vendedor </h1>
{%endblock titulo%}

{% block contenido %}

<div class = "conteiner">
    <h3 class = "mb-4" > Detalles del vendedor </h3>
    <p> Nombre =<i> {{vendedor.nombre}}</i></p>
    <p> Apellido =<i> {{vendedor.apellido}}</i></p>
    <p> dni =<i> {{vendedor.dni}}</i></p>
    <p> vendedor numero =<i> {{vendedor.num_vendedor}}</i></p>
        

    <a href = "{% url 'AppPagina:vendedor_list'%}"> volver </a>
    
</div>
{% endblock contenido%}

AppPagina/templates/AppPagina/vendedor_update.html
{% extends 'AppPagina/inicio.html' %}
{% load static %}

{%block titulo%}
    <h1 class="mb-5">Editar VendedorDetailView </h1>
{%endblock titulo%}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Editar">
</form>
<a href = "{% url 'AppPagina:vendedor_list'%}"> volver </a>
{%endblock contenido%}